SELECT --OOH.ORG_ID,
       DISTINCT OOL.ACTUAL_SHIPMENT_DATE,
       WST.VEHICLE_NUMBER,
       OOH.ORDER_NUMBER,
       WND.NAME DELIVERY_NUMBER,
       AC.CUSTOMER_NAME,
       OOL.ORDERED_ITEM,
       WDD.ITEM_DESCRIPTION,
       WST.ATTRIBUTE7 DISPATCH_TIME,
       WST.SERVICE_LEVEL VEHICLE_WEIGHT,
       HOU.NAME OPERATING_UNIT     
FROM APPS.OE_ORDER_HEADERS_ALL OOH,
     APPS.OE_ORDER_LINES_ALL OOL,
     APPS.WSH_DELIVERY_DETAILS WDD,
     APPS.WSH_DELIVERY_ASSIGNMENTS WDA,
     APPS.WSH_NEW_DELIVERIES WND,
     APPS.WSH_TRIPS WST,
     APPS.WSH_DELIVERY_STOPS_V WDS,
     APPS.AR_CUSTOMERS AC,
     APPS.HR_OPERATING_UNITS HOU
WHERE OOH.HEADER_ID = OOL.HEADER_ID
AND OOH.ORG_ID = HOU.ORGANIZATION_ID
AND OOL.LINE_ID = WDD.SOURCE_LINE_ID
AND WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
AND WDA.DELIVERY_ID = WND.DELIVERY_ID
AND WDA.DELIVERY_ID = WDS.DELIVERY_ID
AND WDS.TRIP_ID = WST.TRIP_ID
AND AC.CUSTOMER_ID = WDD.CUSTOMER_ID 
AND TRUNC (OOL.ACTUAL_SHIPMENT_DATE) BETWEEN :P_FROM_DATE AND :P_TO_DATE
AND (:P_ORG_ID IS NULL OR OOH.ORG_ID = :P_ORG_ID)
ORDER BY HOU.NAME ASC;